GOOGLE_CLI_ID: 799345782509-p9q1bv58q75d3a278p9q4qq89efkahma.apps.googleusercontent.com
GOOGLE_CLI_SECRET: ks30RtprlGqSY5u-CzvbFpH_
GOOGLE_MAP_API_KEY: AIzaSyD_uuBAaXqk1_3KTSznMHudGWpjPyWjiOc

FACEBOOK_APP_ID: 1012418095773173
FACEBOOK_APP_SECRET: f74480984ebc9c492b3d6cec49b526f9

Bing_map_api: AhmL_540FWm1kATBuCO1ME4pq5KgXIH8uIL6Vr5MKxQas95t0tvN76_spcTwHdHh
