GOOGLE_CLI_ID: 558854276496-t7oi76ovkbhdv2ai4q28erhvlck2rp5d.apps.googleusercontent.com
GOOGLE_CLI_SECRET: 7MLZOi8qGjFC_hzY-JAIu18O
GOOGLE_MAP_API_KEY: AIzaSyD_uuBAaXqk1_3KTSznMHudGWpjPyWjiOc

FACEBOOK_APP_ID: 1012418095773173
FACEBOOK_APP_SECRET: f74480984ebc9c492b3d6cec49b526f9

Bing_map_api: AhmL_540FWm1kATBuCO1ME4pq5KgXIH8uIL6Vr5MKxQas95t0tvN76_spcTwHdHh

ZAMMI_FACEBOOK_APP_ID: 408672046471243
ZAMMI_FACEBOOK_APP_SECRET: 4d417d1318e79abf05b9e9479cb0427d