GOOGLE_CLI_ID: 558854276496-t7oi76ovkbhdv2ai4q28erhvlck2rp5d.apps.googleusercontent.com
GOOGLE_CLI_SECRET: 7MLZOi8qGjFC_hzY-JAIu18O
GOOGLE_MAP_API_KEY: AIzaSyD_uuBAaXqk1_3KTSznMHudGWpjPyWjiOc

FACEBOOK_APP_ID: 592659358195791
FACEBOOK_APP_SECRET: 15c61747f9c0c55a2b7dea6e3920de4f

Bing_map_api: AhmL_540FWm1kATBuCO1ME4pq5KgXIH8uIL6Vr5MKxQas95t0tvN76_spcTwHdHh